"""Restructure Alerts

Revision ID: 28766c039041
Revises: 9e0cc7c1fcd1
Create Date: 2023-04-20 14:31:57.288306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28766c039041'
down_revision = '9e0cc7c1fcd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('alert_receiver_fkey', 'alert', type_='foreignkey')
    op.drop_column('alert', 'receiver')
    op.drop_column('alert', 'modify_ts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('modify_ts', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('alert', sa.Column('receiver', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('alert_receiver_fkey', 'alert', 'receiver', ['receiver'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
