"""Fix Fetcher

Revision ID: 9e0cc7c1fcd1
Revises: d8db90e53214
Create Date: 2023-04-20 13:57:28.511856

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e0cc7c1fcd1'
down_revision = 'd8db90e53214'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fetcher', 'fetch_data',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_column('fetcher', 'name')
    op.add_column('receiver', sa.Column('receiver_body', sa.JSON(), nullable=False))
    op.drop_column('receiver', 'body')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fetcher', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('fetcher', 'fetch_data',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.add_column('receiver',
                  sa.Column('body', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('receiver', 'receiver_body')
    # ### end Alembic commands ###
