"""Resctucture Metrics

Revision ID: ac7b835b5a6a
Revises: 28766c039041
Create Date: 2023-04-24 10:35:29.760461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac7b835b5a6a'
down_revision = '28766c039041'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric', sa.Column('time_delta', sa.Float(), nullable=True))
    op.drop_column('metric', 'create_ts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric', sa.Column('create_ts', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('metric', 'time_delta')
    # ### end Alembic commands ###
